// __mocks__/usuariosMock.js

export const usuariosMock = [
  {
    activo: true,
    _id: "6811a47aebf66546dbed5910",
    nombre: "superadmin",
    email: "superadmin@example.com",
    role: "superadministrador",
    accessCode: "amorosin",
    __v: 0,
  },
  {
    _id: "68182491f95fac4349dc3a17",
    nombre: "Mario Benedetti",
    email: "mbenedetti@gmail.com",
    role: "tecnico",
    activo: false,
    __v: 0,
  },
  {
    _id: "681abeef01f846019099a2b8",
    nombre: "Tyrone Myers",
    email: "tyrone@backyardigans.com",
    role: "tecnico",
    activo: false,
    __v: 0,
  },
  {
    activo: true,
    _id: "681ac17f938603903245fc68",
    nombre: "Tasha Smith",
    email: "tasha@backyardigans.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681ad61efe3ac27adc42a26b",
    nombre: "Juan Pérez",
    email: "juanperez@example.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681b71ecd36a6b2557080c9e",
    nombre: "Raul Gonzales",
    email: "rgonzales@realmadrid.es",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681b7387d36a6b2557080ca8",
    nombre: "Mario Ballotelli",
    email: "mbalotelli@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681b745dd36a6b2557080cb4",
    nombre: "Marina Gold",
    email: "marinagold@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681b7df58ea5aadc2aa6f420",
    nombre: "cchrisstiamm",
    email: "cchrisstiamm@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681b85668ea5aadc2aa6f43a",
    nombre: "gal gadot",
    email: "galgadot@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681ba28df570b13caef910eb",
    nombre: "Bruce Wayne",
    email: "brucewayne@waynecorps.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681babb46c41c4ef4a5af577",
    nombre: "Bradley Palomino",
    email: "gmbrandk@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681c1e140b2742801cd5737d",
    nombre: "Cristian Cuevq",
    email: "ccueva@cienciano.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681d732839dea091eaac49ec",
    nombre: "Jose Balta",
    email: "josebalta@gmail.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "681e616b77d87aeb83d172cb",
    nombre: "Barry Allen",
    email: "wonderwoman@waynecorps.com",
    role: "tecnico",
    __v: 0,
  },
  {
    activo: true,
    _id: "682a7df703ed1abe9a965307",
    nombre: "Paulina Rubio",
    email: "prubio@televisa.mx",
    role: "tecnico",
    __v: 0,
  },
];
